### ISSUE TITLE
timeout error 

### ISSUE THREAD

**Issue by einarbey** [cohesity/cohesity-nagios-plugin#5]
when i try to run check_cohesity_protection_runs.py -w 2 -c 3 -d 2 with this settings i get timeout error

but work if i reduce days to 1 

ERROR:cohesity_management_sdk.controllers.protection_runs_controller:30s
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cohesity_management_sdk/controllers/protection_runs_controller.py", line 126, in get_protection_runs
    _context = self.execute_request(_request, name = 'get_protection_runs')
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cohesity_management_sdk/controllers/base_controller.py", line 76, in execute_request
    response = func(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cohesity_management_sdk/http/requests_client.py", line 65, in execute_as_string
    return self.convert_response(response, False)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cohesity_management_sdk/http/requests_client.py", line 103, in convert_response
    return HttpResponse(response.status_code, response.headers, response.text)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/models.py", line 858, in text
    encoding = self.apparent_encoding
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/models.py", line 728, in apparent_encoding
    return chardet.detect(self.content)['encoding']
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/chardet/__init__.py", line 38, in detect
    detector.feed(byte_str)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/chardet/universaldetector.py", line 211, in feed
    if prober.feed(byte_str) == ProbingState.FOUND_IT:
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/chardet/charsetgroupprober.py", line 71, in feed
    state = prober.feed(byte_str)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/chardet/sbcharsetprober.py", line 97, in feed
    self._total_seqs += 1
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/nagiosplugin/platform/posix.py", line 12, in timeout_handler
    raise nagiosplugin.Timeout('{0}s'.format(t))
nagiosplugin.error.Timeout: 30s
COHESITY_PROTECTION_RUN_STATUS UNKNOWN: Timeout: check execution aborted after 30s

**Comment by meni2029** [comment]
Hi, we don't have this issue in our environment, but you could try to increase the plugin timeout with argument `-t`
